GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Ash Ketchum",
    "username": "pikaboy5000",
    "password": "pipikachu"
}

###

POST http://localhost:3003/api/users/login 
Content-Type: application/json 

{
    "username": "pikaboy5000",
    "password": "pipikachu"
}